[project]
name = "rgwml"
version = "0.0.23"
authors = [
  { name="Ryan Gerard Wilson", email="ryangerardwilson@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/ryangerardwilson/rgwml_py"
Issues = "https://github.com/ryangerardwilson/rgwml_py"
